module Alchemist
    NAME = LocaleKey::ALCHEMIST_NAME
    INTRO_DIALOG = LocaleKey::ALCHEMIST_INTRO_DIALOG
    IDLE_DIALOGS = LocaleKey::ALCHEMIST_IDLE_DIALOGS
    CONVERSATION_STARTER = LocaleKey::ALCHEMIST_CONVERSATION_STARTER
    CONVERSATION_KEEPER = LocaleKey::ALCHEMIST_CONVERSATION_KEEPER
    REPEAT_INTRO = LocaleKey::DIAL_ALCHEMIST_REPEAT
    UNKNOWN_DIALOGS = LocaleKey::ALCHEMIST_UNKNOWN_DIALOGS
    PICTURE = 'alchemist'
    DIALOGS = [
        Dialog.new(
            DialogID::ALLIANCE,
            LocaleKey::DIAL_ALCHEMIST_KEY_ALLIANCE,
            LocaleKey::DIAL_ALCHEMIST_TXT_ALLIANCE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_ALLIANCE
        ),
        Dialog.new(
            DialogID::ESCOFFION,
            LocaleKey::DIAL_ALCHEMIST_KEY_ESCOFFION,
            LocaleKey::DIAL_ALCHEMIST_TXT_ESCOFFION,
            LocaleKey::DIAL_ALCHEMIST_INTRO_ESCOFFION
        ),
        Dialog.new(
            DialogID::TELECRYSTAL,
            LocaleKey::DIAL_ALCHEMIST_KEY_TELECRYSTAL,
            LocaleKey::DIAL_ALCHEMIST_TXT_TELECRYSTAL,
            LocaleKey::DIAL_ALCHEMIST_INTRO_TELECRYSTAL
        ),
        Dialog.new(
            DialogID::HEALTH_POTION,
            LocaleKey::DIAL_ALCHEMIST_KEY_HEALTH_POTION,
            LocaleKey::DIAL_ALCHEMIST_TXT_HEALTH_POTION
        ),
        Dialog.new(
            DialogID::LOST_KNIGHT,
            LocaleKey::DIAL_ALCHEMIST_KEY_LOST_KNIGHT,
            LocaleKey::DIAL_ALCHEMIST_TXT_LOST_KNIGHT
        ),
        Dialog.new(
            DialogID::GOBLINS,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOBLINS,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOBLINS,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOBLINS
        ),
        Dialog.new(
            DialogID::SLIMES,
            LocaleKey::DIAL_ALCHEMIST_KEY_SLIME,
            LocaleKey::DIAL_ALCHEMIST_TXT_SLIME
        ),
        Dialog.new(
            DialogID::UNDEAD,
            LocaleKey::DIAL_ALCHEMIST_KEY_UNDEAD,
            LocaleKey::DIAL_ALCHEMIST_TXT_UNDEAD
        ),
        Dialog.new(
            DialogID::RESUSCITATE,
            LocaleKey::DIAL_ALCHEMIST_KEY_RESUSCITATE,
            LocaleKey::DIAL_ALCHEMIST_TXT_RESUSCITATE
        ),
        Dialog.new(
            DialogID::DUNGEON_INTERIOR,
            LocaleKey::DIAL_ALCHEMIST_KEY_DUNGEON_INSIDE,
            LocaleKey::DIAL_ALCHEMIST_TXT_DUNGEON_INSIDE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_DUNGEON_INSIDE
        ),
        Dialog.new(
            DialogID::DUNGEON,
            LocaleKey::DIAL_ALCHEMIST_KEY_DUNGEON,
            LocaleKey::DIAL_ALCHEMIST_TXT_DUNGEON,
            LocaleKey::DIAL_ALCHEMIST_INTRO_DUNGEON
        ),
        Dialog.new(
            DialogID::HOLY_EMPIRE,
            LocaleKey::DIAL_ALCHEMIST_KEY_HOLY_EMPIRE,
            LocaleKey::DIAL_ALCHEMIST_TXT_HOLY_EMPIRE
        ),
        Dialog.new(
            DialogID::SUPPLIER,
            LocaleKey::DIAL_ALCHEMIST_KEY_SUPPLIER,
            LocaleKey::DIAL_ALCHEMIST_TXT_SUPPLIER
        ),
        Dialog.new(
            DialogID::ORIGIN,
            LocaleKey::DIAL_ALCHEMIST_KEY_ORIGIN,
            LocaleKey::DIAL_ALCHEMIST_TXT_ORIGIN
        ),
        Dialog.new(
            DialogID::NAME,
            LocaleKey::DIAL_ALCHEMIST_KEY_NAME,
            LocaleKey::DIAL_ALCHEMIST_TXT_NAME
        ),
        Dialog.new(
            DialogID::AGE,
            LocaleKey::DIAL_ALCHEMIST_KEY_AGE,
            LocaleKey::DIAL_ALCHEMIST_TXT_AGE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_AGE
        ),
        Dialog.new(
            DialogID::GENDER,
            LocaleKey::DIAL_ALCHEMIST_KEY_GENDER,
            LocaleKey::DIAL_ALCHEMIST_TXT_GENDER,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GENDER
        ),
        Dialog.new(
            DialogID::INTELLIGENCE,
            LocaleKey::DIAL_ALCHEMIST_KEY_INTELLIGENCE,
            LocaleKey::DIAL_ALCHEMIST_TXT_INTELLIGENCE
        ),
        Dialog.new(
            DialogID::RECOMMENDATION,
            LocaleKey::DIAL_ALCHEMIST_KEY_RECOMMENDATION,
            LocaleKey::DIAL_ALCHEMIST_TXT_RECOMMENDATION
        ),
        Dialog.new(
            DialogID::ADVICES,
            LocaleKey::DIAL_ALCHEMIST_KEY_ADVICES,
            LocaleKey::DIAL_ALCHEMIST_TXT_ADVICES,
            LocaleKey::DIAL_ALCHEMIST_INTRO_ADVICES
        ),
        Dialog.new(
            DialogID::DISCOUNTS,
            LocaleKey::DIAL_ALCHEMIST_KEY_DISCOUNTS,
            LocaleKey::DIAL_ALCHEMIST_TXT_DISCOUNTS,
            LocaleKey::DIAL_ALCHEMIST_INTRO_DISCOUNTS
        ),
        Dialog.new(
            DialogID::TOO_EXPENSIVE,
            LocaleKey::DIAL_ALCHEMIST_KEY_TOO_EXPENSIVE,
            LocaleKey::DIAL_ALCHEMIST_TXT_TOO_EXPENSIVE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_TOO_EXPENSIVE
        ),
        Dialog.new(
            DialogID::HAVE_YOU,
            LocaleKey::DIAL_ALCHEMIST_KEY_HAVE_YOU,
            LocaleKey::DIAL_ALCHEMIST_TXT_HAVE_YOU
        ),
        Dialog.new(
            DialogID::FUCK_YOU,
            LocaleKey::DIAL_ALCHEMIST_KEY_FUCK_YOU,
            LocaleKey::DIAL_ALCHEMIST_TXT_FUCK_YOU,
            LocaleKey::DIAL_ALCHEMIST_INTRO_FUCK_YOU
        ),
        Dialog.new(
            DialogID::GET_LOST,
            LocaleKey::DIAL_ALCHEMIST_KEY_GET_LOST,
            LocaleKey::DIAL_ALCHEMIST_TXT_GET_LOST,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GET_LOST
        ),
        Dialog.new(
            DialogID::THREAT,
            LocaleKey::DIAL_ALCHEMIST_KEY_THREAT,
            LocaleKey::DIAL_ALCHEMIST_TXT_THREAT,
            LocaleKey::DIAL_ALCHEMIST_INTRO_THREAT
        ),
        Dialog.new(
            DialogID::WEATHER,
            LocaleKey::DIAL_ALCHEMIST_KEY_WEATHER,
            LocaleKey::DIAL_ALCHEMIST_TXT_WEATHER
        ),
        Dialog.new(
            DialogID::SEASON,
            LocaleKey::DIAL_ALCHEMIST_KEY_SEASON,
            LocaleKey::DIAL_ALCHEMIST_TXT_SEASON,
            LocaleKey::DIAL_ALCHEMIST_INTRO_SEASON
        ),
        Dialog.new(
            DialogID::CALLING,
            LocaleKey::DIAL_ALCHEMIST_KEY_MERCHANT_NAME,
            LocaleKey::DIAL_ALCHEMIST_TXT_MERCHANT_NAME
        ),
        Dialog.new(
            DialogID::NOT_FROM_HERE,
            LocaleKey::DIAL_ALCHEMIST_KEY_NOT_FROM_HERE,
            LocaleKey::DIAL_ALCHEMIST_TXT_NOT_FROM_HERE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_NOT_FROM_HERE
        ),
        Dialog.new(
            DialogID::VILLAGE,
            LocaleKey::DIAL_ALCHEMIST_KEY_VILLAGE,
            LocaleKey::DIAL_ALCHEMIST_TXT_VILLAGE
        ),
        Dialog.new(
            DialogID::ADVENTURER,
            LocaleKey::DIAL_ALCHEMIST_KEY_ADVENTURER,
            LocaleKey::DIAL_ALCHEMIST_TXT_ADVENTURER
        ),
        Dialog.new(
            DialogID::YEAR,
            LocaleKey::DIAL_ALCHEMIST_KEY_YEAR,
            LocaleKey::DIAL_ALCHEMIST_TXT_YEAR
        ),
        Dialog.new(
            DialogID::GOLD,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOLD,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOLD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOLD
        ),
        Dialog.new(
            DialogID::NOT_HELPING,
            LocaleKey::DIAL_ALCHEMIST_KEY_NOT_HELPING,
            LocaleKey::DIAL_ALCHEMIST_TXT_NOT_HELPING
        ),
        Dialog.new(
            DialogID::STUPID,
            LocaleKey::DIAL_ALCHEMIST_KEY_STUPID,
            LocaleKey::DIAL_ALCHEMIST_TXT_STUPID
        ),
        Dialog.new(
            DialogID::OTHER_GOD,
            LocaleKey::DIAL_ALCHEMIST_KEY_OTHER_GOD,
            LocaleKey::DIAL_ALCHEMIST_TXT_OTHER_GOD
        ),
        Dialog.new(
            DialogID::GOD,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOD,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOD
        ),
        Dialog.new(
            DialogID::HELLO,
            LocaleKey::DIAL_ALCHEMIST_KEY_HELLO,
            LocaleKey::DIAL_ALCHEMIST_TXT_HELLO
        )
    ]
end
