class Alchemist < CharacterData
    NAME = LocaleKey::ALCHEMIST_NAME
    INTRO_DIALOG = LocaleKey::ALCHEMIST_INTRO_DIALOG
    IDLE_DIALOGS = LocaleKey::ALCHEMIST_IDLE_DIALOGS
    CONVERSATION_STARTER = LocaleKey::ALCHEMIST_CONVERSATION_STARTER
    CONVERSATION_KEEPER = LocaleKey::ALCHEMIST_CONVERSATION_KEEPER
    REPEAT_INTRO = LocaleKey::DIAL_ALCHEMIST_REPEAT
    UNKNOWN_DIALOGS = LocaleKey::ALCHEMIST_UNKNOWN_DIALOGS
    PICTURE = 'alchemist'
    NAME_KNOWN = AlchemistAquinted
    PLAYER_NICKNAME = LocaleKey::ALCHEMIST_NICKNAME
    DIALOGS = [
        Dialog.new(
            DialogID::NAME,
            LocaleKey::DIAL_KEY_PLAYER_NAME,
            LocaleKey::DIAL_ALCHEMIST_TXT_AQUINTENCE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_AQUINTENCE,
            DialogID::ASK_NAME,
            Dialog::NO_REQUIREMENTS,
            -> (player, npc) {player.add_status(NAME_KNOWN.new)}
        ),
        Dialog.new(
            DialogID::ALLIANCE,
            LocaleKey::DIAL_ALCHEMIST_KEY_ALLIANCE,
            LocaleKey::DIAL_ALCHEMIST_TXT_ALLIANCE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_ALLIANCE
        ),
        Dialog.new(
            DialogID::GUILD,
            LocaleKey::DIAL_ALCHEMIST_KEY_GUILD,
            LocaleKey::DIAL_ALCHEMIST_TXT_GUILD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GUILD
        ),
        Dialog.new(
            DialogID::CAT_EARS,
            LocaleKey::DIAL_ALCHEMIST_KEY_CAT_EARS,
            LocaleKey::DIAL_ALCHEMIST_TXT_CAT_EARS,
            LocaleKey::DIAL_ALCHEMIST_INTRO_CAT_EARS
        ),
        Dialog.new(
            DialogID::ESCOFFION,
            LocaleKey::DIAL_ALCHEMIST_KEY_ESCOFFION,
            LocaleKey::DIAL_ALCHEMIST_TXT_ESCOFFION,
            LocaleKey::DIAL_ALCHEMIST_INTRO_ESCOFFION
        ),
        Dialog.new(
            DialogID::TELECRYSTAL,
            LocaleKey::DIAL_ALCHEMIST_KEY_TELECRYSTAL,
            LocaleKey::DIAL_ALCHEMIST_TXT_TELECRYSTAL,
            LocaleKey::DIAL_ALCHEMIST_INTRO_TELECRYSTAL
        ),
        Dialog.new(
            DialogID::HEALTH_POTION,
            LocaleKey::DIAL_ALCHEMIST_KEY_HEALTH_POTION,
            LocaleKey::DIAL_ALCHEMIST_TXT_HEALTH_POTION
        ),
        Dialog.new(
            DialogID::HEALTH_PELLETS,
            LocaleKey::DIAL_ALCHEMIST_KEY_HEALTH_PELLET,
            LocaleKey::DIAL_ALCHEMIST_TXT_HEALTH_PELLET,
            LocaleKey::DIAL_ALCHEMIST_INTRO_HEALTH_PELLET
        ),
        Dialog.new(
            DialogID::AMETHYST,
            LocaleKey::DIAL_ALCHEMIST_KEY_AMETHYST,
            LocaleKey::DIAL_ALCHEMIST_TXT_AMETHYST,
            LocaleKey::DIAL_ALCHEMIST_INTRO_AMETHYST
        ),
        Dialog.new(
            DialogID::LOST_KNIGHT,
            LocaleKey::DIAL_ALCHEMIST_KEY_LOST_KNIGHT,
            LocaleKey::DIAL_ALCHEMIST_TXT_LOST_KNIGHT
        ),
        Dialog.new(
            DialogID::MARTON,
            LocaleKey::DIAL_ALCHEMIST_KEY_MARTON,
            LocaleKey::DIAL_ALCHEMIST_TXT_MARTON,
            LocaleKey::DIAL_ALCHEMIST_INTRO_MARTON
        ),
        Dialog.new(
            DialogID::BLACKSMITH,
            LocaleKey::DIAL_ALCHEMIST_KEY_BLACKSMITH,
            LocaleKey::DIAL_ALCHEMIST_TXT_BLACKSMITH
        ),
        Dialog.new(
            DialogID::GOBLINS,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOBLINS,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOBLINS,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOBLINS
        ),
        Dialog.new(
            DialogID::SLIMES,
            LocaleKey::DIAL_ALCHEMIST_KEY_SLIME,
            LocaleKey::DIAL_ALCHEMIST_TXT_SLIME
        ),
        Dialog.new(
            DialogID::UNDEAD,
            LocaleKey::DIAL_ALCHEMIST_KEY_UNDEAD,
            LocaleKey::DIAL_ALCHEMIST_TXT_UNDEAD
        ),
        Dialog.new(
            DialogID::RESUSCITATE,
            LocaleKey::DIAL_ALCHEMIST_KEY_RESUSCITATE,
            LocaleKey::DIAL_ALCHEMIST_TXT_RESUSCITATE
        ),
        Dialog.new(
            DialogID::DUNGEON_INTERIOR,
            LocaleKey::DIAL_ALCHEMIST_KEY_DUNGEON_INSIDE,
            LocaleKey::DIAL_ALCHEMIST_TXT_DUNGEON_INSIDE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_DUNGEON_INSIDE
        ),
        Dialog.new(
            DialogID::DUNGEON,
            LocaleKey::DIAL_ALCHEMIST_KEY_DUNGEON,
            LocaleKey::DIAL_ALCHEMIST_TXT_DUNGEON,
            LocaleKey::DIAL_ALCHEMIST_INTRO_DUNGEON
        ),
        Dialog.new(
            DialogID::KING,
            LocaleKey::DIAL_ALCHEMIST_KEY_KING,
            LocaleKey::DIAL_ALCHEMIST_TXT_KING
        ),
        Dialog.new(
            DialogID::MOURRE,
            LocaleKey::DIAL_ALCHEMIST_KEY_MOURRE,
            LocaleKey::DIAL_ALCHEMIST_TXT_MOURRE
        ),
        Dialog.new(
            DialogID::LIVROU,
            LocaleKey::DIAL_ALCHEMIST_KEY_LIVROU,
            LocaleKey::DIAL_ALCHEMIST_TXT_LIVROU
        ),
        Dialog.new(
            DialogID::HOLY_EMPIRE,
            LocaleKey::DIAL_ALCHEMIST_KEY_HOLY_EMPIRE,
            LocaleKey::DIAL_ALCHEMIST_TXT_HOLY_EMPIRE
        ),
        Dialog.new(
            DialogID::SUPPLIER,
            LocaleKey::DIAL_ALCHEMIST_KEY_SUPPLIER,
            LocaleKey::DIAL_ALCHEMIST_TXT_SUPPLIER
        ),
        Dialog.new(
            DialogID::ORIGIN,
            LocaleKey::DIAL_ALCHEMIST_KEY_ORIGIN,
            LocaleKey::DIAL_ALCHEMIST_TXT_ORIGIN
        ),
        Dialog.new(
            DialogID::FATHER,
            LocaleKey::DIAL_ALCHEMIST_KEY_FATHER,
            LocaleKey::DIAL_ALCHEMIST_TXT_FATHER,
            LocaleKey::DIAL_ALCHEMIST_INTRO_FATHER
        ),
        Dialog.new(
            DialogID::ASK_NAME,
            LocaleKey::DIAL_ALCHEMIST_KEY_NAME,
            LocaleKey::DIAL_ALCHEMIST_TXT_ASK_NAME,
            Dialog::NO_INTRO,
            Dialog::NO_PRECEDENT_DIAL_REQ,
            -> (player) {return !player.has_status?(NAME_KNOWN)}
        ),
        Dialog.new(
            DialogID::NAME,
            LocaleKey::DIAL_ALCHEMIST_KEY_NAME,
            LocaleKey::DIAL_ALCHEMIST_TXT_NAME
        ),
        Dialog.new(
            DialogID::AGE,
            LocaleKey::DIAL_ALCHEMIST_KEY_AGE,
            LocaleKey::DIAL_ALCHEMIST_TXT_AGE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_AGE
        ),
        Dialog.new(
            DialogID::GENDER,
            LocaleKey::DIAL_ALCHEMIST_KEY_GENDER,
            LocaleKey::DIAL_ALCHEMIST_TXT_GENDER,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GENDER
        ),
        Dialog.new(
            DialogID::INTELLIGENCE,
            LocaleKey::DIAL_ALCHEMIST_KEY_INTELLIGENCE,
            LocaleKey::DIAL_ALCHEMIST_TXT_INTELLIGENCE
        ),
        Dialog.new(
            DialogID::RECOMMENDATION,
            LocaleKey::DIAL_ALCHEMIST_KEY_RECOMMENDATION,
            LocaleKey::DIAL_ALCHEMIST_TXT_RECOMMENDATION
        ),
        Dialog.new(
            DialogID::ADVICES,
            LocaleKey::DIAL_ALCHEMIST_KEY_ADVICES,
            LocaleKey::DIAL_ALCHEMIST_TXT_ADVICES,
            LocaleKey::DIAL_ALCHEMIST_INTRO_ADVICES
        ),
        Dialog.new(
            DialogID::DISCOUNTS,
            LocaleKey::DIAL_ALCHEMIST_KEY_DISCOUNTS,
            LocaleKey::DIAL_ALCHEMIST_TXT_DISCOUNTS,
            LocaleKey::DIAL_ALCHEMIST_INTRO_DISCOUNTS
        ),
        Dialog.new(
            DialogID::TOO_EXPENSIVE,
            LocaleKey::DIAL_ALCHEMIST_KEY_TOO_EXPENSIVE,
            LocaleKey::DIAL_ALCHEMIST_TXT_TOO_EXPENSIVE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_TOO_EXPENSIVE
        ),
        Dialog.new(
            DialogID::HAVE_YOU,
            LocaleKey::DIAL_ALCHEMIST_KEY_HAVE_YOU,
            LocaleKey::DIAL_ALCHEMIST_TXT_HAVE_YOU
        ),
        Dialog.new(
            DialogID::FUCK_YOU,
            LocaleKey::DIAL_ALCHEMIST_KEY_FUCK_YOU,
            LocaleKey::DIAL_ALCHEMIST_TXT_FUCK_YOU,
            LocaleKey::DIAL_ALCHEMIST_INTRO_FUCK_YOU
        ),
        Dialog.new(
            DialogID::GET_LOST,
            LocaleKey::DIAL_ALCHEMIST_KEY_GET_LOST,
            LocaleKey::DIAL_ALCHEMIST_TXT_GET_LOST,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GET_LOST
        ),
        Dialog.new(
            DialogID::THREAT,
            LocaleKey::DIAL_ALCHEMIST_KEY_THREAT,
            LocaleKey::DIAL_ALCHEMIST_TXT_THREAT,
            LocaleKey::DIAL_ALCHEMIST_INTRO_THREAT
        ),
        Dialog.new(
            DialogID::WEATHER,
            LocaleKey::DIAL_ALCHEMIST_KEY_WEATHER,
            LocaleKey::DIAL_ALCHEMIST_TXT_WEATHER
        ),
        Dialog.new(
            DialogID::SEASON,
            LocaleKey::DIAL_ALCHEMIST_KEY_SEASON,
            LocaleKey::DIAL_ALCHEMIST_TXT_SEASON,
            LocaleKey::DIAL_ALCHEMIST_INTRO_SEASON
        ),
        Dialog.new(
            DialogID::NOT_FROM_HERE,
            LocaleKey::DIAL_ALCHEMIST_KEY_NOT_FROM_HERE,
            LocaleKey::DIAL_ALCHEMIST_TXT_NOT_FROM_HERE,
            LocaleKey::DIAL_ALCHEMIST_INTRO_NOT_FROM_HERE
        ),
        Dialog.new(
            DialogID::VILLAGE,
            LocaleKey::DIAL_ALCHEMIST_KEY_VILLAGE,
            LocaleKey::DIAL_ALCHEMIST_TXT_VILLAGE
        ),
        Dialog.new(
            DialogID::ADVENTURER,
            LocaleKey::DIAL_ALCHEMIST_KEY_ADVENTURER,
            LocaleKey::DIAL_ALCHEMIST_TXT_ADVENTURER
        ),
        Dialog.new(
            DialogID::YEAR,
            LocaleKey::DIAL_ALCHEMIST_KEY_YEAR,
            LocaleKey::DIAL_ALCHEMIST_TXT_YEAR
        ),
        Dialog.new(
            DialogID::GOLD,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOLD,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOLD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOLD
        ),
        Dialog.new(
            DialogID::NOT_HELPING,
            LocaleKey::DIAL_ALCHEMIST_KEY_NOT_HELPING,
            LocaleKey::DIAL_ALCHEMIST_TXT_NOT_HELPING
        ),
        Dialog.new(
            DialogID::STUPID,
            LocaleKey::DIAL_ALCHEMIST_KEY_STUPID,
            LocaleKey::DIAL_ALCHEMIST_TXT_STUPID
        ),
        Dialog.new(
            DialogID::OTHER_GOD,
            LocaleKey::DIAL_ALCHEMIST_KEY_OTHER_GOD,
            LocaleKey::DIAL_ALCHEMIST_TXT_OTHER_GOD
        ),
        Dialog.new(
            DialogID::GOD,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOD,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOD
        ),
        Dialog.new(
            DialogID::QUEST,
            LocaleKey::DIAL_ALCHEMIST_KEY_QUEST,
            LocaleKey::DIAL_ALCHEMIST_TXT_QUEST,
            LocaleKey::DIAL_ALCHEMIST_INTRO_QUEST
        ),
        Dialog.new(
            DialogID::HELLO,
            LocaleKey::DIAL_ALCHEMIST_KEY_HELLO,
            LocaleKey::DIAL_ALCHEMIST_TXT_HELLO
        ),
        Dialog.new(
            DialogID::JOKE,
            LocaleKey::DIAL_ALCHEMIST_KEY_JOKE,
            LocaleKey::DIAL_ALCHEMIST_TXT_JOKE
        ),
        Dialog.new(
            DialogID::BAD,
            LocaleKey::DIAL_ALCHEMIST_KEY_BAD,
            LocaleKey::DIAL_ALCHEMIST_TXT_BAD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_BAD,
            DialogID::HOW_YOU_DOIN
        ),
        Dialog.new(
            DialogID::GOOD,
            LocaleKey::DIAL_ALCHEMIST_KEY_GOOD,
            LocaleKey::DIAL_ALCHEMIST_TXT_GOOD,
            LocaleKey::DIAL_ALCHEMIST_INTRO_GOOD,
            DialogID::HOW_YOU_DOIN
        ),
        Dialog.new(
            DialogID::NEUTRAL,
            LocaleKey::DIAL_ALCHEMIST_KEY_NEUTRAL,
            LocaleKey::DIAL_ALCHEMIST_TXT_NEUTRAL,
            LocaleKey::DIAL_ALCHEMIST_INTRO_NEUTRAL,
            DialogID::HOW_YOU_DOIN
        ),
        Dialog.new(
            DialogID::HOW_YOU_DOIN,
            LocaleKey::DIAL_ALCHEMIST_KEY_HOW_YOU_DOIN,
            LocaleKey::DIAL_ALCHEMIST_TXT_HOW_YOU_DOIN
        ),
        Dialog.new(
            DialogID::CALLING,
            LocaleKey::DIAL_ALCHEMIST_KEY_MERCHANT_NAME,
            LocaleKey::DIAL_ALCHEMIST_TXT_MERCHANT_NAME
        ),
        Dialog.new(
            DialogID::ASK_NAME,
            Dialog::NO_TRIGGER_NEEDED,
            LocaleKey::DIAL_ALCHEMIST_TXT_WRONG_NAME,
            LocaleKey::DIAL_ALCHEMIST_INTRO_WRONG_NAME,
            DialogID::ASK_NAME,
            -> (player) {!player.has_status?(NAME_KNOWN)}
        )
    ]
end
