module Blacksmith
    NAME = LocaleKey::BLACKSMITH_NAME
    INTRO_DIALOG = LocaleKey::BLACKSMITH_INTRO_DIALOG
    IDLE_DIALOGS = LocaleKey::BLACKSMITH_IDLE_DIALOGS
    CONVERSATION_STARTER = LocaleKey::BLACKSMITH_CONVERSATION_STARTER
    CONVERSATION_KEEPER = LocaleKey::BLACKSMITH_CONVERSATION_KEEPER
    REPEAT_INTRO = LocaleKey::DIAL_BLACKSMITH_REPEAT
    UNKNOWN_DIALOGS = LocaleKey::BLACKSMITH_UNKNOWN_DIALOGS
    PICTURE = 'merchant'
    NAME_KNOWN = AlchemistAquinted
    PLAYER_NICKNAME = LocaleKey::BLACKSMITH_NICKNAME
    DIALOGS = []
end
