class GoblinGuard < CharacterData
    NAME = LocaleKey::GOBLIN_GUARD_NAME
    INTRO_DIALOG = LocaleKey::GOBLIN_GUARD_INTRO_DIALOG
    IDLE_DIALOGS = LocaleKey::GOBLIN_GUARD_IDLE_DIALOGS
    CONVERSATION_STARTER = LocaleKey::GOBLIN_GUARD_CONVERSATION_STARTER
    CONVERSATION_KEEPER = LocaleKey::GOBLIN_GUARD_CONVERSATION_KEEPER
    REPEAT_INTRO = LocaleKey::DIAL_GOBLIN_GUARD_REPEAT
    UNKNOWN_DIALOGS = LocaleKey::GOBLIN_GUARD_UNKNOWN_DIALOGS
    PICTURE = 'alchemist'
    NAME_KNOWN = GoblinGuardAquinted
    PLAYER_NICKNAME = LocaleKey::GOBLIN_GUARD_NICKNAME
    COMBAT_BODY = FighterGoblin
    START_FIGHT_ACTION = -> (character, room) {
        room.anger_passives
    }
    ROOM_DESCRIPTION = LocaleKey::GUARD_NPC_DESCRIPTION
    DIALOGS = [
    ]
end
