module Recruter
    NAME = ''
    INTRO_DIALOG = ''
    IDLE_DIALOGS = LocaleKey::PLACEHOLDER_ARRAY
    CONVERSATION_STARTER = LocaleKey::PLACEHOLDER_ARRAY
    CONVERSATION_KEEPER = LocaleKey::PLACEHOLDER_ARRAY
    REPEAT_INTRO = LocaleKey::PLACEHOLDER_ARRAY
    DIALOGS = []
    UNKNOWN_DIALOGS = LocaleKey::PLACEHOLDER_ARRAY
    PICTURE = 'recruter'
end
