module Monsters
    # Female
    BAT_F = "chauve-souris"
    GOBLIN_F = "gobline"
    HARPIE_F = "harpie"
    KNIGHT_F = "chevalière"
    PRISONNER_F = "prisonnière oubliée"
    SPIDER_F = "araignée"
    ZOMBIE_F = "mort-vivante"
    # Male
    GOBLIN_M = "goblin"
    KNIGHT_M = "chevalier"
    PRISONNER_M = "prisonnier oublié"
    SKELLETON_M = "squelette"
    SLIME_M = "slime"
    SPRIGGAN_M = "spriggan"
    ZOMBIE_M = "mort-vivant"
end

module Rooms
    # Female
    ALCOVE_F = "pièce"
    CELL_F = "cellule"
    CHAMBER_F = "chambre"
    GEOLLE_F = "geolle"
    ROOM_F = "salle"
    TORTURE_CHAMBER_F = "chambre de torture"
    # Male
    CORRIDOR_M = "couloir"
    REFECTORY_M = "réfectoire"
    SLEEP_PLACE_M = "dortoir"
    TUNNEL_M = "tunnel"
end

module Bodyparts
    # Female
    HEAD_F = "tête"
    # Male
    ARM_M = "bras"
end

module Adjectives
    # Female
    AGILE_F = "agile"
    ANCIENT_F = "ancienne"
    ANGRY_F = "énervée"
    AUTHORITARIAN_F = "autoritaire"
    BIG_F = "grosse"
    BLUISH_F = "bleutée"
    COLD_F = "froide"
    DARK_F = "sombre"
    DRY_F = "sèche"
    DUSTY_F = "poussièreuse"
    GREEN_F = "verte"
    GREYISH_F = "grisée"
    HUMID_F = "humide"
    ISOLATED_F = "isolée"
    JADED_F = "blasée"
    LEFT_F = "gauche"
    LONG_F = "longue"
    LOST_F = "perdue"
    MUSCULAR_F = "musclée"
    NARROW_F = "étroite"
    RIGHT_F = "droite"
    RUINED_F = "en ruine"
    SCARY_F = "terrifiante"
    SCOUT_F = "éclaireuse"
    SILENT_F = "silencieuse"
    SMALL_F = "petite"
    SMART_F = "intelligente"
    SPACIOUS_F = "spacieuse"
    STRANGE_F = "étrange"
    TALL_F = "grande"
    TIRED_F = "fatiguée"
    WARY_F = "méfiante"
    WORRIED_F = "inquiète"
    WORRYING_F = "inquiétante"
    # Male
    AGILE_M = "agile"
    ANCIENT_M = "ancien"
    ANGRY_M = "énervé"
    AUTHORITARIAN_M = "autoritaire"
    BIG_M = "gros"
    BLUISH_M = "bleuté"
    COLD_M = "froid"
    DARK_M = "sombre"
    DRY_M = "sec"
    DUSTY_M = "poussiéreux"
    GREEN_M = "vert"
    GREYISH_M = "grisé"
    HUMID_M = "humide"
    JADED_M = "blasé"
    ISOLATED_M = "isolé"
    LEFT_M = "gauche"
    LONG_M = "long"
    LOST_M = "perdu"
    MUSCULAR_M = "musclé"
    NARROW_M = "étroit"
    RIGHT_M = "droit"
    RUINED_M = "en ruine"
    SCARY_M = "terrifiant"
    SCOUT_M = "éclaireur"
    SILENT_M = "silencieux"
    SMALL_M = "petit"
    SMART_M = "intelligent"
    SPACIOUS_M = "spacieux"
    STRANGE_M = "étrange"
    TALL_M = "grand"
    TIRED_M = "fatigué"
    WARY_M = "méfiant"
    WORRIED_M = "inquiet"
    WORRYING_M = "inquiétant"
end
