module BossCellRequireKey
    ENTRY_QUESTION = Locale::KEY_BOSS_CELL_REQ_QUESTION
    ENTRY_MESSAGE = Locale::KEY_BOSS_CELL_REQ_ENTRY
    NO_ENTRY_MESSAGE = Locale::KEY_BOSS_CELL_REQ_REFUSE
    IMPOSSIBLE_ENTRY_MESSAGE = Locale::KEY_BOSS_CELL_REQ_CANT
    REQUIRED_ITEMS = [PrisonKey]
    ONCE = true
end
