module BossGolemConfirm
    ENTRY_QUESTION = LocaleKey::BOSS_GOLEM_CONFIRM_QUESTION
    ENTRY_MESSAGE = LocaleKey::BOSS_GOLEM_CONFIRM_ENTRY
    NO_ENTRY_MESSAGE = LocaleKey::BOSS_GOLEM_CONFIRM_REFUSE
    REQUIRED_ITEMS = []
    ONCE = true
end
